-- liquibase formatted sql

-- changeset javaded78:1728414532389-1
CREATE TABLE IF NOT EXISTS t_user
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_email                      VARCHAR(255)                            NOT NULL,
    c_password                   VARCHAR(255)                            NOT NULL,
    c_role                       VARCHAR(255)                            NOT NULL,
    c_is_account_non_expired     BOOLEAN                                 NOT NULL,
    c_is_account_non_locked      BOOLEAN                                 NOT NULL,
    c_is_credentials_non_expired BOOLEAN                                 NOT NULL,
    c_is_enabled                 BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_user PRIMARY KEY (id)
);

-- changeset javaded78:1728414532389-2
ALTER TABLE t_user
    ADD CONSTRAINT uc_t_user_c_email UNIQUE (c_email);

-- changeset javaded78:1728414532389-3

CREATE TABLE IF NOT EXISTS t_deactivated_token
(
    id           UUID NOT NULL,
    c_keep_until TIMESTAMP NOT NULL CHECK ( c_keep_until > now() ),
    CONSTRAINT pk_t_deactivated_token PRIMARY KEY (id)
);
