server:
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/authentication-service
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  docker:
    compose:
      file: authentication-service/docker/compose.yaml
      lifecycle-management: start_only