server:
  port: 8082

spring:
  config:
    import: optional:file:.env[.properties]

  data:
    mongodb:
      uri: mongodb://profile:profile@localhost:27017/profile-service?readPreference=secondaryPreferred
      username: profile
      password: profile
      host: localhost
      port: 27017
      database: profile-service
      authenticationDatabase: profile-service
      auto-index-creation: true

    redis:
      host: localhost
      port: 6379
      password: redis

  jpa:
    open-in-view: false

  cache:
    type: redis
    cache-names: redis-cache

resilience4j:
  circuitbreaker:
    instances:
      storage-service:
        minimum-number-of-calls: 5
        failure-rate-threshold: 50
        sliding-window-size: 10
        wait-duration-in-open-state: 3s

logging:
  level:
    io.github.resilience4j.circuitbreaker: trace
    org.springframework.data.mongodb: trace
    org.springframework.data.redis: trace
