CREATE TABLE IF NOT EXISTS t_user
(
    id                           BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_email                      VARCHAR(255)                            NOT NULL,
    c_password                   VARCHAR(255)                            NOT NULL,
    c_username                   VARCHAR(255)                            NOT NULL,
    c_is_account_non_expired     BOOLEAN                                 NOT NULL,
    c_is_account_non_locked      BOOLEAN                                 NOT NULL,
    c_is_credentials_non_expired BOOLEAN                                 NOT NULL,
    c_is_enabled                 BOOLEAN                                 NOT NULL,
    CONSTRAINT pk_t_user PRIMARY KEY (id)
);

ALTER TABLE t_user
    ADD CONSTRAINT uc_t_user_c_email UNIQUE (c_email),
    ADD CONSTRAINT uc_t_user_c_username UNIQUE (c_username);

CREATE TABLE IF NOT EXISTS t_user_authority
(
    id_user     BIGINT                                  NOT NULL,
    c_authority VARCHAR                                 NOT NULL,
    CONSTRAINT pk_t_user_authority PRIMARY KEY (id_user, c_authority),
    CONSTRAINT fk_t_user_authority_on_c_user FOREIGN KEY (id_user) REFERENCES t_user (id) ON DELETE CASCADE ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS t_deactivated_token
(
    id           UUID      NOT NULL,
    c_keep_until TIMESTAMP NOT NULL CHECK ( c_keep_until > now() ),
    CONSTRAINT pk_t_deactivated_token PRIMARY KEY (id)
);
