CREATE TABLE t_activation_code
(
    id                BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    c_user_id         BIGINT,
    c_code            VARCHAR(255),
    c_expiration_time TIMESTAMP WITHOUT TIME ZONE,
    CONSTRAINT pk_t_activation_code PRIMARY KEY (id)
);

ALTER TABLE t_activation_code
    ADD CONSTRAINT uc_t_activation_code_c_user UNIQUE (c_user_id);

ALTER TABLE t_activation_code
    ADD CONSTRAINT fk_t_activation_code_on_c_user FOREIGN KEY (c_user_id) REFERENCES t_user (id);
