server:
  port: 8081

spring:
  application:
    name: email-service
  mail:
    host: smtp.gmail.com
    username: perfumestoreapp@gmail.com
    password: oggmtuvzwyxbvifk
    port: 465
    protocol: smtps
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    consumer:
      group-id: send-email-events
      bootstrap-servers: localhost:9092,localhost:9094,localhost:9096
      isolation-level: READ_COMMITTED
      properties:
        spring.json.trusted.packages: com.javaded78.commons.event

mail:
  debug: false
